# Generated by Django 2.2.3 on 2019-07-12 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190711_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='lastUpdatedByID',
        ),
        migrations.AddField(
            model_name='ticket',
            name='lastUpdatedBy',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='userID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
