# Generated by Django 2.2.3 on 2019-07-12 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190712_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
