# Generated by Django 2.2.3 on 2019-07-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20190712_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='userID',
            field=models.IntegerField(default=0),
        ),
    ]
