# Generated by Django 2.2.3 on 2019-07-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='reviewing', max_length=200),
        ),
    ]
