# Generated by Django 2.2.3 on 2019-07-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20190714_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
