# Generated by Django 2.2.3 on 2019-07-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20190717_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='lastUpdatedDateTime',
            field=models.DateTimeField(),
        ),
    ]
