# Generated by Django 2.2.3 on 2019-07-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20190717_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('reviewing', 'Reviewing'), ('in progress', 'In Progress'), ('closed', 'Closed')], default='reviewing', max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature')], max_length=50),
        ),
    ]
