# Generated by Django 2.2.3 on 2019-07-17 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('county', models.CharField(blank=True, max_length=30)),
                ('town_or_city', models.CharField(blank=True, max_length=30)),
                ('postcode', models.CharField(blank=True, max_length=15)),
                ('street1', models.CharField(blank=True, max_length=50)),
                ('street2', models.CharField(blank=True, max_length=50)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
