# Generated by Django 2.2.3 on 2019-07-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('DateTimeCreated', models.DateTimeField(auto_now_add=True)),
                ('userID', models.IntegerField()),
                ('status', models.CharField(default='under review', max_length=200)),
                ('LastUpdatedByID', models.IntegerField()),
                ('LastUpdatedDateTime', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ticket_type', models.CharField(default='bug', max_length=50)),
            ],
        ),
    ]
