# Generated by Django 2.2.3 on 2019-07-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20190712_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='lastUpdatedBy',
            new_name='lastUpdatedByID',
        ),
    ]
